POST http://localhost:4004/odata/v4/myservice/update_status HTTP/1.1
Content-Type: application/json

{
      "VBELN": "4",
      "POSNR": "4",
      "MATNR": null,
      "ORMNG": null,
      "LFIMG": null,
      "VRKME": null,
      "CHARG": null,
      "WERKS": null,
      "ZPACK": null,
      "ZCOMP": null,
      "ZCONS": null,
      "ZSHIPS": null,
      "ZSHIPL": null,
      "ZCANLIP": null,
      "ZZ_STATUSCODE": null,
      "ZZ_CREATED_BY": null,
      "ZZ_CREATED_ON": null,
      "ZZ_UPDATE_BY": null,
      "ZZ_UPDATE_ON": null,
      "Correction": "1"
    }

###

GET http://localhost:4004/odata/v4/myservice/update_status 